name: cache

on:
  workflow_dispatch:
    inputs:
      swatinem:
        description: 'Run swatinem action'
        required: true 
        type: boolean 
      sccache:
        description: 'Run sccache action'
        required: true 
        type: boolean 
      home: # only cache recommended directories in ~/.cargo
        description: 'Run home action'
        required: true 
        type: boolean 
      home_and_target: # cache recommended directories in ~/.cargo/ and target/
        description: 'Run home_and_target action'
        required: true 
        type: boolean 
      home_and_target_v2: # cache recommended directories in ~/.cargo/ and target/ + ~/.cargo/registry/src
        description: 'Run home_and_target action'
        required: true 
        type: boolean 
      full: # cache full ~/.cargo/ and target/
        description: 'Run full action'
        required: true 
        type: boolean 
      restore_mtime:
        description: 'Restore mtime to commit time'
        required: true 
        type: boolean 

env:
  CARGO_INCREMENTAL: 0

jobs:
  swatinem:
    runs-on: ubuntu-latest
    if:  ${{ inputs.swatinem }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: swatinem
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  sccache:
    runs-on: ubuntu-latest
    if:  ${{ inputs.sccache }}
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: "1G"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --no-symlinks sccache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cache/
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  home:
    runs-on: ubuntu-latest
    if:  ${{ inputs.home }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-home-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  home_and_target:
    runs-on: ubuntu-latest
    if:  ${{ inputs.home_and_target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-home_and_target-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  home_and_target_v2:
    runs-on: ubuntu-latest
    if:  ${{ inputs.home_and_target_v2 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/src/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-home_and_target_v2-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  full:
    runs-on: ubuntu-latest
    if:  ${{ inputs.full }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-full-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings
