name: cache

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to run'
        required: true
        default: 'swatinem'
        type: choice
        options:
        - swatinem
        - sccache
        - full # cache ~/.cargo/ and target/
      restore_mtime:
        description: 'Restore mtime to commit time'
        required: true 
        type: boolean 

env:
  CARGO_INCREMENTAL: 0

jobs:
  swatinem-raw:
    runs-on: ubuntu-latest
    if:  ${{ inputs.action == 'swatinem' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: swatinem-raw
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  sccache:
    runs-on: ubuntu-latest
    if:  ${{ inputs.action == 'sccache' }}
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_DIR: ".sccache"
      SCCACHE_CACHE_SIZE: "1G"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --no-symlinks sccache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .sccache/
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings

  full:
    runs-on: ubuntu-latest
    if:  ${{ inputs.action == 'full' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-full-${{ hashFiles('**/Cargo.lock') }}
      - uses: chetan/git-restore-mtime-action@v1
        if: ${{ inputs.restore_mtime }}
      - run: cargo test --locked --no-run
      - run: cargo test --locked --no-fail-fast
      - run: cargo clippy --locked --workspace --tests --no-deps -- -D warnings
